# Travis CI configuration
language: node_js

node_js:
  - node

install: npm install

jobs:
  include:
    - stage: test
      script:
        - npm test
    - stage: build
      script:
        - npm run build
        - npm run dev-dist

# Cache folder setting
cache:
  directories:
    - node_modules
